name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/BookingHotel.sln
    - name: Build
      run: dotnet build src/BookingHotel.sln --no-restore
    - name: Publish
      run: dotnet publish src/BookingHotel.sln --no-build --output ./publish

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/BookingHotel.sln
    - name: Build
      run: dotnet build src/BookingHotel.sln --no-restore
    - name: Test
      run: dotnet test src/BookingHotel.sln --no-build --verbosity normal